-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-03-16 17:06:36 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Capture run of script in file called custorders_schema_output.txt

set echo on
SPOOL property_rental_schema_output.txt
SET DEFINE OFF;

--student id: 30428831
--student name: Tristan Sim

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-03-16 17:14:37 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE DAMAGE CASCADE CONSTRAINTS 
;

DROP TABLE MAINTENANCE CASCADE CONSTRAINTS 
;

DROP TABLE OWNER CASCADE CONSTRAINTS 
;

DROP TABLE PAYMENT CASCADE CONSTRAINTS 
;

DROP TABLE PAYMETHOD CASCADE CONSTRAINTS 
;

DROP TABLE PROPERTY CASCADE CONSTRAINTS 
;

DROP TABLE RENT CASCADE CONSTRAINTS 
;

DROP TABLE TENANT CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE DAMAGE 
    ( 
     dam_no            NUMBER (8)  NOT NULL , 
     dam_datetime      DATE  NOT NULL , 
     rent_agreement_no NUMBER (8)  NOT NULL , 
     dam_type          VARCHAR2 (50)  NOT NULL , 
     dam_cost          NUMBER (8,2)  NOT NULL , 
     pay_no            NUMBER (8)  NOT NULL 
    ) 
;

COMMENT ON COLUMN DAMAGE.dam_no IS 'Damage Number (Surrogate Key & Primary Key)' 
;

COMMENT ON COLUMN DAMAGE.dam_datetime IS 'Damage Date Time (Since Oracle Supports a Special Data Time Variable)' 
;

COMMENT ON COLUMN DAMAGE.rent_agreement_no IS 'Rental Agreement Number (Surrogate Key | Primary Key)' 
;

COMMENT ON COLUMN DAMAGE.dam_type IS 'Damage Type' 
;

COMMENT ON COLUMN DAMAGE.dam_cost IS 'Damage Cost (AUD 3000.00)' 
;

COMMENT ON COLUMN DAMAGE.pay_no IS 'Payment Number (Primary Key)' 
;
CREATE UNIQUE INDEX DAMAGE__IDX ON DAMAGE 
    ( 
     pay_no ASC 
    ) 
;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT DAMAGE_PK PRIMARY KEY ( dam_no ) ;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT damage_uniq_id UNIQUE ( dam_datetime , rent_agreement_no ) ;

CREATE TABLE MAINTENANCE 
    ( 
     prop_no        NUMBER (7)  NOT NULL , 
     maint_datetime DATE  NOT NULL , 
     maint_desc     VARCHAR2 (50)  NOT NULL , 
     maint_cost     NUMBER (8,2)  NOT NULL 
    ) 
;

COMMENT ON COLUMN MAINTENANCE.prop_no IS 'Property Number (Primary Key)' 
;

COMMENT ON COLUMN MAINTENANCE.maint_datetime IS 'Maintanance Date Time' 
;

COMMENT ON COLUMN MAINTENANCE.maint_desc IS 'Maintance Descripton' 
;

COMMENT ON COLUMN MAINTENANCE.maint_cost IS 'Maintanance Cost' 
;

ALTER TABLE MAINTENANCE 
    ADD CONSTRAINT MAINTENANCE_PK PRIMARY KEY ( prop_no, maint_datetime ) ;

CREATE TABLE OWNER 
    ( 
     owner_no         NUMBER (7)  NOT NULL , 
     owner_given_name VARCHAR2 (50) , 
     owner_fam_nam    VARCHAR2 (50) , 
     owner_street     VARCHAR2 (50)  NOT NULL , 
     owner_city       VARCHAR2 (50)  NOT NULL , 
     owner_state      VARCHAR2 (50)  NOT NULL , 
     owner_postcode   CHAR (10)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OWNER.owner_no IS 'Owner Number (Primary Key)' 
;

COMMENT ON COLUMN OWNER.owner_given_name IS 'Owner Given  Name' 
;

COMMENT ON COLUMN OWNER.owner_fam_nam IS 'Owner Family Name' 
;

COMMENT ON COLUMN OWNER.owner_street IS 'Owner Address - Street' 
;

COMMENT ON COLUMN OWNER.owner_city IS 'Owner Address - City' 
;

COMMENT ON COLUMN OWNER.owner_state IS 'Owner Address - State' 
;

COMMENT ON COLUMN OWNER.owner_postcode IS 'Owner Address - Postal Code' 
;

ALTER TABLE OWNER 
    ADD CONSTRAINT OWNER_PK PRIMARY KEY ( owner_no ) ;

CREATE TABLE PAYMENT 
    ( 
     pay_no            NUMBER (8)  NOT NULL , 
     pay_date          DATE  NOT NULL , 
     pay_type          CHAR (1)  NOT NULL , 
     pay_amount        NUMBER (8,2)  NOT NULL , 
     rent_agreement_no NUMBER (8)  NOT NULL , 
     pay_paidby        NUMBER (8)  NOT NULL 
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT check_pay_type 
    CHECK (pay_type IN ('B', 'D', 'R')) 
;

COMMENT ON COLUMN PAYMENT.pay_no IS 'Payment Number (Primary Key)' 
;

COMMENT ON COLUMN PAYMENT.pay_date IS 'Payment Date' 
;

COMMENT ON COLUMN PAYMENT.pay_type IS 'Payment Type (CHECK Constraints: Rent, Bond, Damage)' 
;

COMMENT ON COLUMN PAYMENT.pay_amount IS 'Payment Amount (AUD 1200.00)' 
;

COMMENT ON COLUMN PAYMENT.rent_agreement_no IS 'Rental Agreement Number (Surrogate Key | Primary Key)' 
;

COMMENT ON COLUMN PAYMENT.pay_paidby IS 'Payment Method ID' 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT PAYMENT_PK PRIMARY KEY ( pay_no ) ;

CREATE TABLE PAYMETHOD 
    ( 
     paymethod_id   NUMBER (8)  NOT NULL , 
     paymethod_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PAYMETHOD.paymethod_id IS 'Payment Method ID' 
;

COMMENT ON COLUMN PAYMETHOD.paymethod_name IS 'Payment Method Name' 
;

ALTER TABLE PAYMETHOD 
    ADD CONSTRAINT PAYMETHOD_PK PRIMARY KEY ( paymethod_id ) ;

CREATE TABLE PROPERTY 
    ( 
     prop_no       NUMBER (7)  NOT NULL , 
     prop_street   VARCHAR2 (50)  NOT NULL , 
     prop_city     VARCHAR2 (50)  NOT NULL , 
     prop_state    VARCHAR2 (50)  NOT NULL , 
     prop_postcode VARCHAR2 (50)  NOT NULL , 
     prop_value    NUMBER (10)  NOT NULL , 
     owner_no      NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PROPERTY.prop_no IS 'Property Number (Primary Key)' 
;

COMMENT ON COLUMN PROPERTY.prop_street IS 'Property Address - Street' 
;

COMMENT ON COLUMN PROPERTY.prop_city IS 'Property Address - City' 
;

COMMENT ON COLUMN PROPERTY.prop_state IS 'Property Address - State' 
;

COMMENT ON COLUMN PROPERTY.prop_postcode IS 'Property Address - Postcode' 
;

COMMENT ON COLUMN PROPERTY.prop_value IS 'Property Value (Up to 1 Billion)' 
;

COMMENT ON COLUMN PROPERTY.owner_no IS 'Owner Number (Primary Key)' 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT PROPERTY_PK PRIMARY KEY ( prop_no ) ;

CREATE TABLE RENT 
    ( 
     rent_agreement_no    NUMBER (8)  NOT NULL , 
     prop_no              NUMBER (7)  NOT NULL , 
     rent_lease_startdate DATE  NOT NULL , 
     rent_weekly_rate     NUMBER (8,2)  NOT NULL , 
     rent_bond            NUMBER (8,2)  NOT NULL , 
     rent_lease_period    NUMBER (8)  NOT NULL , 
     tenant_no            NUMBER (8)  NOT NULL 
    ) 
;

COMMENT ON COLUMN RENT.rent_agreement_no IS 'Rental Agreement Number (Surrogate Key | Primary Key)' 
;

COMMENT ON COLUMN RENT.prop_no IS 'Property Number (Primary Key)' 
;

COMMENT ON COLUMN RENT.rent_lease_startdate IS 'Rent Lease Date (Primary Key)' 
;

COMMENT ON COLUMN RENT.rent_weekly_rate IS 'Rental Weekly Rate (AUD 3000.00)' 
;

COMMENT ON COLUMN RENT.rent_bond IS 'Rental Bond' 
;

COMMENT ON COLUMN RENT.rent_lease_period IS 'Rental Lease Period' 
;

COMMENT ON COLUMN RENT.tenant_no IS 'Tenant Number (Primary Key)' 
;

ALTER TABLE RENT 
    ADD CONSTRAINT RENT_PK PRIMARY KEY ( rent_agreement_no ) ;

ALTER TABLE RENT 
    ADD CONSTRAINT rent_uniq_id UNIQUE ( prop_no , rent_lease_startdate ) ;

CREATE TABLE TENANT 
    ( 
     tenant_no         NUMBER (8)  NOT NULL , 
     tenant_given_name VARCHAR2 (50) , 
     tenant_fam_name   VARCHAR2 (50) , 
     tenant_street     VARCHAR2 (50)  NOT NULL , 
     tenant_city       VARCHAR2 (50)  NOT NULL , 
     tenant_state      VARCHAR2 (50)  NOT NULL , 
     tenant_postcode   CHAR 
--  WARNING: CHAR size not specified 
                     NOT NULL , 
     tenant_phone_no   CHAR (10) 
    ) 
;

COMMENT ON COLUMN TENANT.tenant_no IS 'Tenant Number (Primary Key)' 
;

COMMENT ON COLUMN TENANT.tenant_given_name IS 'Tenant Given Name' 
;

COMMENT ON COLUMN TENANT.tenant_fam_name IS 'Tenant Family Name' 
;

COMMENT ON COLUMN TENANT.tenant_street IS 'Tenant Address - Street' 
;

COMMENT ON COLUMN TENANT.tenant_city IS 'Tenant Address - City' 
;

COMMENT ON COLUMN TENANT.tenant_state IS 'Tenant Address - State' 
;

COMMENT ON COLUMN TENANT.tenant_postcode IS 'Tenant Address - Postal Code' 
;

COMMENT ON COLUMN TENANT.tenant_phone_no IS 'Tenant Phone Number' 
;

ALTER TABLE TENANT 
    ADD CONSTRAINT TENANT_PK PRIMARY KEY ( tenant_no ) ;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT damage_rent_REL FOREIGN KEY 
    ( 
     rent_agreement_no
    ) 
    REFERENCES RENT 
    ( 
     rent_agreement_no
    ) 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT owner_property_REL FOREIGN KEY 
    ( 
     owner_no
    ) 
    REFERENCES OWNER 
    ( 
     owner_no
    ) 
;

ALTER TABLE DAMAGE 
    ADD CONSTRAINT payment_damage FOREIGN KEY 
    ( 
     pay_no
    ) 
    REFERENCES PAYMENT 
    ( 
     pay_no
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT payment_rent_REL FOREIGN KEY 
    ( 
     rent_agreement_no
    ) 
    REFERENCES RENT 
    ( 
     rent_agreement_no
    ) 
;

ALTER TABLE PAYMENT 
    ADD CONSTRAINT paymethod_payment_REL FOREIGN KEY 
    ( 
     pay_paidby
    ) 
    REFERENCES PAYMETHOD 
    ( 
     paymethod_id
    ) 
;

ALTER TABLE MAINTENANCE 
    ADD CONSTRAINT property_maint_REL FOREIGN KEY 
    ( 
     prop_no
    ) 
    REFERENCES PROPERTY 
    ( 
     prop_no
    ) 
;

ALTER TABLE RENT 
    ADD CONSTRAINT property_rent_REL FOREIGN KEY 
    ( 
     prop_no
    ) 
    REFERENCES PROPERTY 
    ( 
     prop_no
    ) 
;

ALTER TABLE RENT 
    ADD CONSTRAINT tenant_rent_REL FOREIGN KEY 
    ( 
     tenant_no
    ) 
    REFERENCES TENANT 
    ( 
     tenant_no
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 1

SPOOL off
set echo off