
-- Drop SQL Tables Created From Customer Orders

DROP TABLE CUSTOMER CASCADE CONSTRAINTS 
;

DROP TABLE ORDERLINE CASCADE CONSTRAINTS 
;

DROP TABLE ORDERS CASCADE CONSTRAINTS 
;

DROP TABLE PROD_CATEGORY CASCADE CONSTRAINTS 
;

DROP TABLE PRODUCT CASCADE CONSTRAINTS 
;