
-- Project: Assessment 1 Logical
-- Description: Fire Damage Assessment System SQL Schema Generated from Oracle Data Modeler
-- Name: Tristan Sim and Max Ruzic
-- Group: 26

set echo on
SPOOL fdas_schema_output.txt
SET DEFINE OFF;

-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-03-31 15:04:18 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



DROP TABLE ASSESSOR CASCADE CONSTRAINTS 
;

DROP TABLE BUILDING CASCADE CONSTRAINTS 
;

DROP TABLE DAMAGE_ASSESSMENT CASCADE CONSTRAINTS 
;

DROP TABLE EMPLOYMENT CASCADE CONSTRAINTS 
;

DROP TABLE FIRE_EVENT CASCADE CONSTRAINTS 
;

DROP TABLE FIRE_EVENT_LGA CASCADE CONSTRAINTS 
;

DROP TABLE INSURER CASCADE CONSTRAINTS 
;

DROP TABLE LOCAL_GOV_AREA CASCADE CONSTRAINTS 
;

DROP TABLE OWNER CASCADE CONSTRAINTS 
;

DROP TABLE PROPERTY CASCADE CONSTRAINTS 
;

DROP TABLE PROPERTY_TYPE CASCADE CONSTRAINTS 
;

DROP TABLE VISIT CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ASSESSOR 
    ( 
     assessor_id         NUMBER (12)  NOT NULL , 
     assessor_given_name VARCHAR2 (50)  NOT NULL , 
     assessor_fam_name   VARCHAR2 (50)  NOT NULL , 
     assessor_phone_no   CHAR (12)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ASSESSOR.assessor_id IS 'Assessor ID (Primary Key)' 
;

COMMENT ON COLUMN ASSESSOR.assessor_given_name IS 'Assessor Given Name' 
;

COMMENT ON COLUMN ASSESSOR.assessor_fam_name IS 'Assessor fam Name' 
;

COMMENT ON COLUMN ASSESSOR.assessor_phone_no IS 'Assessor Phone Number' 
;

ALTER TABLE ASSESSOR 
    ADD CONSTRAINT ASSESSOR_PK PRIMARY KEY ( assessor_id ) ;

CREATE TABLE BUILDING 
    ( 
     building_id             NUMBER (16)  NOT NULL , 
     property_id             NUMBER (12)  NOT NULL , 
     building_no             NUMBER (12)  NOT NULL , 
     building_class          NUMBER (2) DEFAULT 1  NOT NULL , 
     building_approval_date  DATE  NOT NULL , 
     building_size_sq_meters NUMBER (12,2) DEFAULT 0  NOT NULL , 
     building_lga_value      NUMBER (15,2) DEFAULT 0  NOT NULL , 
     building_insured        CHAR (1) DEFAULT 'N'  NOT NULL , 
     insurer_id              NUMBER (12) 
    ) 
;

ALTER TABLE BUILDING 
    ADD CONSTRAINT CHK_BUILDING_CLASS 
    CHECK (building_class IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)) 
;

ALTER TABLE BUILDING 
    ADD CONSTRAINT CHK_BUILDING_INSURANCE_COVER 
    CHECK (building_insured IN ('N', 'Y')) 
;

COMMENT ON COLUMN BUILDING.building_id IS 'Building ID (Primary Surrogate Key acting as a Unique Identifier for Each Building)' 
;

COMMENT ON COLUMN BUILDING.property_id IS 'National Property ID (Primary Key)' 
;

COMMENT ON COLUMN BUILDING.building_no IS 'Building Number (Not Unique Globally, unique only to each Property. i.e. 1,2,3)' 
;

COMMENT ON COLUMN BUILDING.building_class IS 'Building class based on the National Construction Code Classes (Victorian Building Authority): 1=Residential Buildings, 2=Apartment Buildings, 3=Residential Buildings (Other than Class 1 and 2), 4=Single Domestics Dwelling, 5=Office Buildings, 6=Retail Buildings, 7=Carparks/Storage/Warehouses, 8=Factories, 9=Public Building, 10=Non-Habitable Structure' 
;

COMMENT ON COLUMN BUILDING.building_approval_date IS 'Building Construction Approval Data' 
;

COMMENT ON COLUMN BUILDING.building_size_sq_meters IS 'Building Size in Square Meters (2500.20 Square Meters)' 
;

COMMENT ON COLUMN BUILDING.building_lga_value IS 'Building LGA Value ($ 12,000,000.00) ' 
;

COMMENT ON COLUMN BUILDING.building_insured IS 'Does Building Has Insurance Coverage (Constraint: Y= Yes | N= No)' 
;

COMMENT ON COLUMN BUILDING.insurer_id IS 'Insurer ID (Primary Key)' 
;

ALTER TABLE BUILDING 
    ADD CONSTRAINT BUILDING_PK PRIMARY KEY ( building_id ) ;

ALTER TABLE BUILDING 
    ADD CONSTRAINT BUILDING_NK UNIQUE ( property_id , building_no ) ;

CREATE TABLE DAMAGE_ASSESSMENT 
    ( 
     assessment_id                NUMBER (16)  NOT NULL , 
     fire_id                      NUMBER (12)  NOT NULL , 
     building_id                  NUMBER (16)  NOT NULL , 
     assessor_id                  NUMBER (12) , 
     assessment_damage_cost       NUMBER (12,2) DEFAULT 0  NOT NULL , 
     assessment_totally_destroyed CHAR (1) DEFAULT 'N'  NOT NULL 
    ) 
;

ALTER TABLE DAMAGE_ASSESSMENT 
    ADD CONSTRAINT CHK_ASSESSMENT_DESTROYED 
    CHECK (assessment_totally_destroyed IN ('N', 'Y')) 
;

COMMENT ON COLUMN DAMAGE_ASSESSMENT.assessment_id IS 'Damage Assessment ID (Primary Surrogate Key)' 
;

COMMENT ON COLUMN DAMAGE_ASSESSMENT.fire_id IS 'Fire Event ID (Primary Key)' 
;

COMMENT ON COLUMN DAMAGE_ASSESSMENT.building_id IS 'Building ID (Primary Surrogate Key acting as a Unique Identifier for Each Building)' 
;

COMMENT ON COLUMN DAMAGE_ASSESSMENT.assessor_id IS 'Assessor ID (Primary Key)' 
;

COMMENT ON COLUMN DAMAGE_ASSESSMENT.assessment_damage_cost IS 'Total Damage Cost to the Building ($350,000.50). Business Rule: This is a derived attribute for uninsured buildings. When BUILDING.building_insured = ''''N'''', the assessment_damage_cost should equal BUILDING.building_lga_value. For insured buildings, this value is determined by the insurance assessor.' 
;

COMMENT ON COLUMN DAMAGE_ASSESSMENT.assessment_totally_destroyed IS 'Building Totally Damaged? (Constraint: Y = Yes | N = No)' 
;

ALTER TABLE DAMAGE_ASSESSMENT 
    ADD CONSTRAINT DAMAGE_ASSESSMENT_PK PRIMARY KEY ( assessment_id ) ;

ALTER TABLE DAMAGE_ASSESSMENT 
    ADD CONSTRAINT DAMAGE_ASSESSMENT_NK UNIQUE ( fire_id , building_id ) ;

CREATE TABLE EMPLOYMENT 
    ( 
     employment_id         NUMBER (12)  NOT NULL , 
     assessor_id           NUMBER (12)  NOT NULL , 
     insurer_id            NUMBER (12)  NOT NULL , 
     employment_start_date DATE  NOT NULL , 
     employment_end_date   DATE 
    ) 
;

COMMENT ON COLUMN EMPLOYMENT.employment_id IS 'Employment ID (Primary Surrogate Key)' 
;

COMMENT ON COLUMN EMPLOYMENT.assessor_id IS 'Assessor ID (Primary Key)' 
;

COMMENT ON COLUMN EMPLOYMENT.insurer_id IS 'Insurer ID (Primary Key)' 
;

COMMENT ON COLUMN EMPLOYMENT.employment_start_date IS 'Employment Start Date' 
;

COMMENT ON COLUMN EMPLOYMENT.employment_end_date IS 'Employment End Date (Cannot be before the Start Date)' 
;

ALTER TABLE EMPLOYMENT 
    ADD CONSTRAINT EMPLOYMENT_PK PRIMARY KEY ( employment_id ) ;

ALTER TABLE EMPLOYMENT 
    ADD CONSTRAINT EMPLOYMENT_NK UNIQUE ( assessor_id , insurer_id , employment_start_date ) ;

CREATE TABLE FIRE_EVENT 
    ( 
     fire_id              NUMBER (12)  NOT NULL , 
     fire_parent_event_id NUMBER (12) , 
     fire_name            VARCHAR2 (50)  NOT NULL , 
     fire_start_date      DATE  NOT NULL , 
     fire_latitude        NUMBER (9,6) DEFAULT 0  NOT NULL , 
     fire_longitude       NUMBER (9,6) DEFAULT 0  NOT NULL , 
     fire_hectares_burnt  NUMBER (10,2) DEFAULT 0.00  NOT NULL , 
     fire_lives_lost      NUMBER (10) DEFAULT 0  NOT NULL , 
     fire_total_damage    NUMBER (12) DEFAULT 0  NOT NULL 
    ) 
;

ALTER TABLE FIRE_EVENT 
    ADD CONSTRAINT CHK_HECTARES_BURNT 
    CHECK (fire_hectares_burnt >= 0) 
;

COMMENT ON COLUMN FIRE_EVENT.fire_id IS 'Fire Event ID (Primary Key)' 
;

COMMENT ON COLUMN FIRE_EVENT.fire_parent_event_id IS 'Fire Event ID (Primary Key)' 
;

COMMENT ON COLUMN FIRE_EVENT.fire_name IS 'Fire Event Name' 
;

COMMENT ON COLUMN FIRE_EVENT.fire_start_date IS 'Fire Event Start Date' 
;

COMMENT ON COLUMN FIRE_EVENT.fire_latitude IS 'Fire Event Latitude (e.g. 38.895122)' 
;

COMMENT ON COLUMN FIRE_EVENT.fire_longitude IS 'Fire Event Longitude (e.g. -35.245622)' 
;

COMMENT ON COLUMN FIRE_EVENT.fire_hectares_burnt IS 'Fire Event Hectares Burnt (When a New Fire is added to FDAS, it starts at 0.00 hectares | Must be Positive Value)' 
;

COMMENT ON COLUMN FIRE_EVENT.fire_lives_lost IS 'Lives Lost due to this Fire Event (Example: 10 Lives)' 
;

COMMENT ON COLUMN FIRE_EVENT.fire_total_damage IS 'Total Damage Caused by Fire Event ($ 1,250,000.00)' 
;

ALTER TABLE FIRE_EVENT 
    ADD CONSTRAINT FIRE_EVENT_PK PRIMARY KEY ( fire_id ) ;

CREATE TABLE FIRE_EVENT_LGA 
    ( 
     fire_event_lga_id NUMBER (12)  NOT NULL , 
     fire_id           NUMBER (12)  NOT NULL , 
     lga_code_id       NUMBER (12)  NOT NULL 
    ) 
;

COMMENT ON COLUMN FIRE_EVENT_LGA.fire_event_lga_id IS 'Fire Event LGA ID (Primary Surrogate Key)' 
;

COMMENT ON COLUMN FIRE_EVENT_LGA.fire_id IS 'Fire Event ID (Primary Key)' 
;

COMMENT ON COLUMN FIRE_EVENT_LGA.lga_code_id IS 'Local Government Area Code ID (Primary Key)' 
;

ALTER TABLE FIRE_EVENT_LGA 
    ADD CONSTRAINT FIRE_EVENT_LGA_PK PRIMARY KEY ( fire_event_lga_id ) ;

ALTER TABLE FIRE_EVENT_LGA 
    ADD CONSTRAINT FIRE_EVENT_LGA_NK UNIQUE ( fire_id , lga_code_id ) ;

CREATE TABLE INSURER 
    ( 
     insurer_id       NUMBER (12)  NOT NULL , 
     insurer_name     VARCHAR2 (50)  NOT NULL , 
     insurer_phone_no CHAR (12)  NOT NULL 
    ) 
;

COMMENT ON COLUMN INSURER.insurer_id IS 'Insurer ID (Primary Key)' 
;

COMMENT ON COLUMN INSURER.insurer_name IS 'Insurer Name (i.e Chubbs Insurance)' 
;

COMMENT ON COLUMN INSURER.insurer_phone_no IS 'Insurer Phone Number' 
;

ALTER TABLE INSURER 
    ADD CONSTRAINT INSURER_PK PRIMARY KEY ( insurer_id ) ;

CREATE TABLE LOCAL_GOV_AREA 
    ( 
     lga_code_id           NUMBER (12)  NOT NULL , 
     lga_name              VARCHAR2 (50)  NOT NULL , 
     lga_size_hectares     NUMBER (10,2)  NOT NULL , 
     lga_ceo_name          VARCHAR2 (50)  NOT NULL , 
     lga_bushfire_phone_no CHAR (12)  NOT NULL 
    ) 
;

COMMENT ON COLUMN LOCAL_GOV_AREA.lga_code_id IS 'Local Government Area Code ID (Primary Key)' 
;

COMMENT ON COLUMN LOCAL_GOV_AREA.lga_name IS 'Local Government Area Name' 
;

COMMENT ON COLUMN LOCAL_GOV_AREA.lga_size_hectares IS 'Local Government Area Size in Hectares (e.g. 125.23 Hectares)' 
;

COMMENT ON COLUMN LOCAL_GOV_AREA.lga_ceo_name IS 'Local Government Area Chief Executive Officer''s Name' 
;

COMMENT ON COLUMN LOCAL_GOV_AREA.lga_bushfire_phone_no IS 'Local Government Area Bushfire Emergency Contact Number' 
;

ALTER TABLE LOCAL_GOV_AREA 
    ADD CONSTRAINT LOCAL_GOV_AREA_PK PRIMARY KEY ( lga_code_id ) ;

CREATE TABLE OWNER 
    ( 
     owner_id       NUMBER (12)  NOT NULL , 
     owner_name     VARCHAR2 (50)  NOT NULL , 
     owner_phone_no CHAR (12)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OWNER.owner_id IS 'Owner ID (Primary Key)' 
;

COMMENT ON COLUMN OWNER.owner_name IS 'Owner Name (First and Last Name: Thomas Lane)' 
;

COMMENT ON COLUMN OWNER.owner_phone_no IS 'Owner Phone Number' 
;

ALTER TABLE OWNER 
    ADD CONSTRAINT OWNER_PK PRIMARY KEY ( owner_id ) ;

CREATE TABLE PROPERTY 
    ( 
     property_id            NUMBER (12)  NOT NULL , 
     property_street        VARCHAR2 (50)  NOT NULL , 
     property_town          VARCHAR2 (50)  NOT NULL , 
     property_postcode      VARCHAR2 (50)  NOT NULL , 
     property_size_hectares NUMBER (10,2) DEFAULT 0  NOT NULL , 
     lga_code_id            NUMBER (12)  NOT NULL , 
     property_type_id       NUMBER (12)  NOT NULL , 
     owner_id               NUMBER (12)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PROPERTY.property_id IS 'National Property ID (Primary Key)' 
;

COMMENT ON COLUMN PROPERTY.property_street IS 'Property Address: Street' 
;

COMMENT ON COLUMN PROPERTY.property_town IS 'Property Address: Town' 
;

COMMENT ON COLUMN PROPERTY.property_postcode IS 'Property Address: Postal Code' 
;

COMMENT ON COLUMN PROPERTY.property_size_hectares IS 'Property Size in Hectares (e.g. 15.26 hectares)' 
;

COMMENT ON COLUMN PROPERTY.lga_code_id IS 'Local Government Area Code ID (Primary Key)' 
;

COMMENT ON COLUMN PROPERTY.property_type_id IS 'Property Type ID (Primary Key)' 
;

COMMENT ON COLUMN PROPERTY.owner_id IS 'Owner ID (Primary Key)' 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT PROPERTY_PK PRIMARY KEY ( property_id ) ;

CREATE TABLE PROPERTY_TYPE 
    ( 
     property_type_id   NUMBER (12)  NOT NULL , 
     property_type_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PROPERTY_TYPE.property_type_id IS 'Property Type ID (Primary Key)' 
;

COMMENT ON COLUMN PROPERTY_TYPE.property_type_name IS 'Property Type Name (i.e. Resendential, Strata, Farm and etc.)' 
;

ALTER TABLE PROPERTY_TYPE 
    ADD CONSTRAINT PROPERTY_TYPE_PK PRIMARY KEY ( property_type_id ) ;

CREATE TABLE VISIT 
    ( 
     assessment_id         NUMBER (16)  NOT NULL , 
     visit_datetime_arrive DATE  NOT NULL , 
     visit_datetime_depart DATE 
    ) 
;

COMMENT ON COLUMN VISIT.assessment_id IS 'Damage Assessment ID (Primary Surrogate Key)' 
;

COMMENT ON COLUMN VISIT.visit_datetime_arrive IS 'The Date and Time of the Arrival of the Visit' 
;

COMMENT ON COLUMN VISIT.visit_datetime_depart IS 'The Date and Time of the Departure of the Visit' 
;

ALTER TABLE VISIT 
    ADD CONSTRAINT VISIT_PK PRIMARY KEY ( visit_datetime_arrive, assessment_id ) ;

ALTER TABLE BUILDING 
    ADD CONSTRAINT REL_BUILDING_PROPERTY FOREIGN KEY 
    ( 
     property_id
    ) 
    REFERENCES PROPERTY 
    ( 
     property_id
    ) 
;

ALTER TABLE DAMAGE_ASSESSMENT 
    ADD CONSTRAINT REL_DAM_ASSESS_ASSESSOR FOREIGN KEY 
    ( 
     assessor_id
    ) 
    REFERENCES ASSESSOR 
    ( 
     assessor_id
    ) 
;

ALTER TABLE DAMAGE_ASSESSMENT 
    ADD CONSTRAINT REL_DAM_ASSESS_BUILDING FOREIGN KEY 
    ( 
     building_id
    ) 
    REFERENCES BUILDING 
    ( 
     building_id
    ) 
;

ALTER TABLE DAMAGE_ASSESSMENT 
    ADD CONSTRAINT REL_DAM_ASSESS_FIRE_EVENT FOREIGN KEY 
    ( 
     fire_id
    ) 
    REFERENCES FIRE_EVENT 
    ( 
     fire_id
    ) 
;

ALTER TABLE VISIT 
    ADD CONSTRAINT REL_DAM_ASSESS_VISIT FOREIGN KEY 
    ( 
     assessment_id
    ) 
    REFERENCES DAMAGE_ASSESSMENT 
    ( 
     assessment_id
    ) 
;

ALTER TABLE EMPLOYMENT 
    ADD CONSTRAINT REL_EMPLOYMENT_ASSESSOR FOREIGN KEY 
    ( 
     assessor_id
    ) 
    REFERENCES ASSESSOR 
    ( 
     assessor_id
    ) 
;

ALTER TABLE EMPLOYMENT 
    ADD CONSTRAINT REL_EMPLOYMENT_INSURER FOREIGN KEY 
    ( 
     insurer_id
    ) 
    REFERENCES INSURER 
    ( 
     insurer_id
    ) 
;

ALTER TABLE FIRE_EVENT 
    ADD CONSTRAINT REL_FIRE_EVENT_IGNITES FOREIGN KEY 
    ( 
     fire_parent_event_id
    ) 
    REFERENCES FIRE_EVENT 
    ( 
     fire_id
    ) 
;

ALTER TABLE FIRE_EVENT_LGA 
    ADD CONSTRAINT REL_IMPACTS_FIRE_EVENT_LGA FOREIGN KEY 
    ( 
     fire_id
    ) 
    REFERENCES FIRE_EVENT 
    ( 
     fire_id
    ) 
;

ALTER TABLE BUILDING 
    ADD CONSTRAINT REL_INSURER_BUILDING FOREIGN KEY 
    ( 
     insurer_id
    ) 
    REFERENCES INSURER 
    ( 
     insurer_id
    ) 
;

ALTER TABLE FIRE_EVENT_LGA 
    ADD CONSTRAINT REL_INVOLVED_FIRE_EVENT_LGA FOREIGN KEY 
    ( 
     lga_code_id
    ) 
    REFERENCES LOCAL_GOV_AREA 
    ( 
     lga_code_id
    ) 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT REL_OWNER_PROPERTY FOREIGN KEY 
    ( 
     owner_id
    ) 
    REFERENCES OWNER 
    ( 
     owner_id
    ) 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT REL_PROPERTY_LGA FOREIGN KEY 
    ( 
     lga_code_id
    ) 
    REFERENCES LOCAL_GOV_AREA 
    ( 
     lga_code_id
    ) 
;

ALTER TABLE PROPERTY 
    ADD CONSTRAINT REL_PROPERTY_PROPERTY_TYPE FOREIGN KEY 
    ( 
     property_type_id
    ) 
    REFERENCES PROPERTY_TYPE 
    ( 
     property_type_id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             34
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SPOOL off
set echo off