
-- Drop SQL Tables Created From Property Rentals

DROP TABLE DAMAGE CASCADE CONSTRAINTS 
;

DROP TABLE MAINTENANCE CASCADE CONSTRAINTS 
;

DROP TABLE OWNER CASCADE CONSTRAINTS 
;

DROP TABLE PAYMENT CASCADE CONSTRAINTS 
;

DROP TABLE PAYMETHOD CASCADE CONSTRAINTS 
;

DROP TABLE PROPERTY CASCADE CONSTRAINTS 
;

DROP TABLE RENT CASCADE CONSTRAINTS 
;

DROP TABLE TENANT CASCADE CONSTRAINTS 
;
