
/*
Script: SQL Purge all Unused Tables from Oracle Database
Institution: Monash University Australia
Subject: ITO 4132 Introduction to Databases
Database Type:: Oracle SQL Database

Student Name: Tristan Sim 
Last Modified Date: 2nd April 2025

*/

-- This Script is to Purge Tables From the SQL Server

-- Transaction: Drop all Tables

-- DROP TABLE ENROLMENT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE FIT5111_STUDENT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE STUDENT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE UNIT CASCADE CONSTRAINTS PURGE;

-- DROP TABLE ASSESSOR CASCADE CONSTRAINTS PURGE;
-- DROP TABLE BUILDING CASCADE CONSTRAINTS PURGE;
-- DROP TABLE EMPLOYMENT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE FIRE_EVENT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE FIRE_EVENT_LGA CASCADE CONSTRAINTS PURGE;
-- DROP TABLE INSURER CASCADE CONSTRAINTS PURGE;
-- DROP TABLE LOCAL_GOV_AREA CASCADE CONSTRAINTS PURGE;
-- DROP TABLE OWNER CASCADE CONSTRAINTS PURGE;
-- DROP TABLE PROPERTY CASCADE CONSTRAINTS PURGE;
-- DROP TABLE PROPERTY_TYPE CASCADE CONSTRAINTS PURGE;
-- DROP TABLE VISIT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE DAMAGE_ASSESSMENT CASCADE CONSTRAINTS PURGE;

-- DROP TABLE ENROLMENT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE FIT5111_STUDENT CASCADE CONSTRAINTS PURGE;
-- DROP TABLE STUDENT CASCADE CONSTRAINTS PURGE; 
-- DROP TABLE UNIT CASCADE CONSTRAINTS PURGE;
-- DROP SEQUENCE STUDENT_SEQ;

-- Drop Sequences for Assignment 2
DROP SEQUENCE service_seq; 
DROP SEQUENCE part_charge_seq; 
DROP SEQUENCE part_purchase_seq;
DROP SEQUENCE part_sale_seq;


-- Drop Tables for Assignment 2
DROP TABLE part_purchase CASCADE CONSTRAINTS PURGE;
DROP TABLE part_sale CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS PURGE; 
DROP TABLE PART CASCADE CONSTRAINTS PURGE;
DROP TABLE PART_CHARGE CASCADE CONSTRAINTS PURGE;
DROP TABLE SERVICE CASCADE CONSTRAINTS PURGE;
DROP TABLE SERVICE_JOB CASCADE CONSTRAINTS PURGE;
DROP TABLE VEHICLE CASCADE CONSTRAINTS PURGE;
DROP TABLE PAY_MODE CASCADE CONSTRAINTS PURGE;
DROP TABLE VENDOR CASCADE CONSTRAINTS PURGE;


-- Purge Oracle Database Recycle Bin
PURGE RECYCLEBIN;